version: "3.9"

services:
  frontend:
    container_name: website_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    container_name: website_backend
    build: ./backend
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    restart: unless-stopped

volumes:
  node_modules: